version: '3.8'

services:
  app:
    build:
      args:
        user: thyerre
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    restart: always
    networks: 
      - docker-laravel

networks:
  docker-laravel:
    driver: bridge