version: '3.8'

services:
  web:
    image: nginx:alpine
    restart: always
    ports:
      - 90:80
    volumes:
      - ./:/var/www/
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - example-network

  php:
    image: php:8.0-fpm
    restart: always
    volumes:
     - ./:/var/www/
    networks:
      - example-network

networks:
  example-network:
    driver: bridge